name=input("Enter your name:")
sem=int(input("Enter your semester:"))
city=input("Enter your city:")
pincode=int(inout("Enter a pincode of your city:"))
print("\n\n\n")
print("Student Name:",name)
print("Semester:",sem)
print("City:",city)
print("Pincode:",pincode)
